sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 111111
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7AHemBu3VDw9R4C3rn
    access-key-secret: gwtebnHlAugQL03rnlYmUlIF5qa65u
    bucket-name: cq-bck
